### PR TITLE
#2Task. ivan.lozovskij

### PR DESCRIPTION
**Pull request by Lozovskij**
https://travis-ci.org/github/Lozovskij/db-assignments/builds/714031974

### CODE REVIEW

**Comment by vramaniuk** [comment]
Dirty PR.
Selection_005
This PR should have only changes related to task2 (mongodb tasks)
66 changed files. In real project it would be completely impossible to find usefull changes and make an review.
I suppose, you have updated your local repo wrong way.
Selection_006
You should just  have made `git pull` to ensure your repo having all the changes that have been made since you forked initial repo.

Please, try to revert this commit 
4767ca3

and update your local repo proper way.

**Comment by vramaniuk** [comment]
Selection_004
Try to decrease the time of performing these tests up to 100 ms. Adding some indexes to specific collections  should help
I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by Lozovskij** [comment]
https://travis-ci.org/github/AisBrestEDU/db-assignments/builds/727628213

**Comment by vramaniuk** [comment]
Closing the PR as accepted! Thanks!

**Pull request closed without merging**
