### PR TITLE
#mongo-tasks. Alexander Zenchyk

### PR DESCRIPTION
**Pull request by zeeenjaaa**
https://travis-ci.org/github/zeeenjaaa/db-assignments/builds/734360647

### CODE REVIEW

**Comment by vramaniuk** [comment]
Selection_009
Try to decrease the time of performing these tests up to 100 ms. Adding some indexes to specific collections  should help

**Comment by vramaniuk** [comment]
I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by zeeenjaaa** [comment]
Thanks! Your hint helped! 
https://travis-ci.org/github/zeeenjaaa/db-assignments/builds/735094485
image

**Comment by vramaniuk** [comment]
Closing the PR as accepted! Thanks!

**Pull request closed without merging**
