### PR TITLE
Mongodb Task Dmitry Gaiduk

### PR DESCRIPTION
**Pull request by IdokkeI**
https://travis-ci.com/github/IdokkeI/db-assignments/builds/181915965

### CODE REVIEW

**Comment by vramaniuk** [comment]
Try to decrease the time of performing these tests up to 100 ms. Adding some indexes to specific collections  should help
Selection_010
I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by IdokkeI** [comment]
Could you check my ui, please? https://idokkei.github.io/skype/

**Comment by vramaniuk** [comment]
> https://travis-ci.com/github/IdokkeI/db-assignments/builds/181915965

You should have provided this 
https://travis-ci.com/github/IdokkeI/db-assignments/builds/183910605

**Comment by vramaniuk** [comment]
Selection_004
Try to improve these queries.
I suppose, adding additional operators between $lookup which goes in a row in your quaries , will help

**Comment by vramaniuk** [comment]
> Could you check my ui, please? https://idokkei.github.io/skype/

As I know , Ilya Mokin is responsible for it

**Comment by vramaniuk** [comment]
I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by IdokkeI** [comment]
https://travis-ci.com/github/IdokkeI/db-assignments/builds/183937510

**Comment by vramaniuk** [comment]
Closing the PR as accepted! Thanks!

**Pull request closed without merging**
