### PR TITLE
Mongo optimization Dmitry Gaiduk

### PR DESCRIPTION
**Pull request by IdokkeI**
https://travis-ci.com/github/IdokkeI/db-assignments/builds/181916045

### CODE REVIEW

**Review by KostyaKov — COMMENTED** [review]
Looks good, but you should also use indexes.

**Comment by KostyaKov** [comment]
Can you add indexes, which will greatly improve performance, please?

**Comment by IdokkeI** [comment]
https://travis-ci.com/github/IdokkeI/db-assignments/builds/183897807

**Comment by IlyaMokin** [comment]
Looking good! but mongodb can't use more than 1 index per '$match'. So, you need only 2 the best indexes for the query.
The PR is accepted

**Pull request closed without merging**
