### PR TITLE
#Mongo_tasks Andrey Yakshuk

### PR DESCRIPTION
**Pull request by andreyPromaster**
https://travis-ci.com/github/andreyPromaster/db-assignments/builds/179805409

### CODE REVIEW

**Comment by vramaniuk** [comment]
Try to decrease the time of performing these tests up to 100 ms. Adding some indexes to specific collections  should help
Selection_009

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by andreyPromaster** [comment]
https://travis-ci.com/github/andreyPromaster/db-assignments/builds/183627063

**Comment by vramaniuk** [comment]
Selection_002
You shouldn't have done these changes in this PR.
You have specific branch 'optimization' for task mongodb optimization task
Selection_003
As the result , we have an error in test
Please, revert changes, related to optimization task
I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by andreyPromaster** [comment]
https://travis-ci.com/github/andreyPromaster/db-assignments/builds/183767028

**Comment by vramaniuk** [comment]
Closing the PR as accepted! Thanks!

**Pull request closed without merging**
