### PR TITLE
#MongoDB-Optimization Task. TapeGhad

### PR DESCRIPTION
**Pull request by TapeGhad**

### CODE REVIEW

**Comment by KostyaKov** [comment]
Can you add travis link to the description, please?

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by TapeGhad** [comment]
https://travis-ci.com/github/TapeGhad/db-assignments/builds/179872723

**Comment by TapeGhad** [comment]
Yes, sure

**Comment by vramaniuk** [comment]
Closing the PR as accepted! Thanks!

**Pull request closed without merging**
