### PR TITLE
Mongo-tasks_Ira S-H

### PR DESCRIPTION
**Pull request by irmir**
https://travis-ci.org/github/irmir/db-assignments/builds/741076923

### CODE REVIEW

**Comment by vramaniuk** [comment]
Selection_014
Try to decrease the time of performing these tests up to 100 ms. Adding some indexes to specific collections  should help

**Comment by vramaniuk** [comment]
I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by irmir** [comment]
> Try to decrease the time of performing these tests up to 100 ms. Adding some indexes to specific collections should help

Here you are! https://travis-ci.org/github/irmir/db-assignments/builds/742065432

**Comment by vramaniuk** [comment]
Closing the PR as accepted! Thanks!

**Pull request closed without merging**
