### PR TITLE
#Mongo_optimization_task. Dmitry Leonov

### PR DESCRIPTION
**Pull request by DmitryLeonov11**
https://travis-ci.com/github/DmitriyLeonov/db-assignments/builds/178805442

### CODE REVIEW

**Comment by KostyaKov** [comment]
PR has redundant changes of other tasks. Can you update PR, please? 

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by DmitryLeonov11** [comment]
https://travis-ci.com/github/DmitriyLeonov/db-assignments/builds/184407363

**Comment by DmitryLeonov11** [comment]
I should use rebase to do this?

**Comment by DmitryLeonov11** [comment]
I reopen this pull request in #146

**Pull request closed without merging**
